version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.24.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.3.0
    - 5.4.0
    - 5.7.0
  - dependency-name: release-it
    versions:
    - 14.6.1
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.13.15
    - 7.13.7
    - 7.13.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.1.1
  - dependency-name: husky
    versions:
    - 5.1.0
    - 6.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.6.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.18
    - 7.13.2
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.17
